language: python

python:
  - "3.6"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env`
  - poetry install

script:
  - coverage run run_tests.py

after_success:
  - coveralls

before_deploy:
  - poetry config repositories.packagr https://api.packagr.app/63cdQSDO/
  - poetry config http-basic.packagr christopherdavies553@gmail.com $PACKAGR_PASSWORD
  - poetry config http-basic.pypi chris140957 $PYPI_PASSWORD

deploy:
  - provider: script
    script: poetry publish --build
    on:
      branch: master

  - provider: script
    script: poetry publish --build -r packagr
    on:
      all_branches: true
